experimentName: Ablustr
trialConcurrency: 1
maxExecDuration: 30h
maxTrialNum: 50
#choice: local, remote, pai   
trainingServicePlatform: local
searchSpacePath: /workspace/search_space.json
useAnnotation: false 
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: python /workspace/adv_detect.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
  maxTrialNumPerGpu: 1
  gpuIndices: "1"